image: Visual Studio 2015
platform: x64
configuration: Release

build_script:
  - cd C:/projects/viphreeqc
  - cmake -DBUILD_SHARED_LIBS:BOOL=ON -G "Visual Studio 14 2015 Win64" .
  - cmake --build . --config Release
  - cd C:/projects/viphreeqc/release
  - dir
